const Strings = {
  signIn: 'Sign In',
  signUp: 'Sign Up',
  exercise: 'Exercise is good for the ˚Soul˚.',
  Hello:'Hello there!',
  I_Am:'I am ',
  contact:'Contact me at: ',
  love:'Love Thy Self!',
  appName:'moresocial',
  appTagLine:'What’s happening where you are?',
  Swipe:'Swipe to Learn More',
  Explore:'Explore',
  Connect:'Connect',
  Grow:'Grow',
  GrowText:'Earn likes and followers to boost your popularity so that more users connect with you and your events',
  ExploreText:'Fly through the map to see the coolest people and events near you as reported by locals',
  ConnectText:'Post things happening around you, share with friends and chat with locals to learn what’s happening now',
  facebookLogin:'Login with facebook',
  linkedLogin:'Login with LinkedIn',
  signUpWork:'Stuff will happen!',
  loginEmailField:'Email Address/Mobile Number',
  EmailChange:'Email Address',
  Invalid:'The values are invalid!',
  Password:'Password',
  invalidCreds:'Your Credentials are Invalid!',
  forgotPassword:'Forgot Password',
  orSignIn:'or sign in with',
  noAccount:'Don’t have an account?',
  forgotPasswordText:'Enter email address or mobile number to reset your password.',
  inValidPassword:'Password must contain atleast a symbol and 6 characters!',
  verification:'Verification Code',
  submit:'Submit',
  verifyText:'The Verification Code was sent to your email address. Please enter below:',
  noCode:'Didn’t receive code?',
  resend:'RESEND ',
  resetPassword:'Reset Password',
  passwordNoMatch:'Your Password\'s do not match!',
  resetPasswordText:'Enter new password below to reset your password.',
  confirmPassword:'Confirm Password',
  NewPassword:'New Password',
  proceed:'proceed',
  verifiedText:'You have successfully verified. Let’s proceed to reset your password.',
  verified:'Verified Successfully',
  validEmail:'Enter a valid email address!',
  resetSucces:'Password Reset Successfully',
  resetSuccesText:'You have successfully reset your password. Please use your new password when signing in.',
  profile:'profile',
  edit:'edit',
  save:'save',
  name: 'Your Name',
  bio:'Enter Your Bio',
  number:'Your Number',
  countryCode:'+91',
  fbUrl:'https://www.facebook.com/Alisha',
  LinkedInUrl:'https://www.linkedin.com/Alisha',
  connectFb:'Connect Your Facebook',
  connectLi:'Connect Your LinkedIn',
  fillDetails: 'Please fill the details below',
  messages:'messages',
  typeMsg:'Your message!',
  delete:'delete',
  users:'users',
  noChats:'No Chats',
};
export default Strings;
